spring:
  application:
    name: TMS
  boot:
    admin:
      client:
        url: "http://localhost:8000"
        username: "admin"
        password: "admin"
management:
  endpoints:
    web:
      exposure:
        include: "*"