spring:
  application:
    name: TMS
  boot:
    admin:
      client:
        url: "http://localhost:8000"
        username: "admin"
        password: "admin"
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: "/Users/xhj/IdeaProjects/Logs/client/output.log"
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"